<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>name</key>
  <string>Basilisk</string>
  <key>scopeName</key>
  <string>source.bslk</string>
  <key>fileTypes</key>
  <array>
    <string>bslk</string>
  </array>
  <key>patterns</key>
  <array>
    <dict><key>include</key><string>#comments</string></dict>
    <dict><key>include</key><string>#strings</string></dict>
    <dict><key>include</key><string>#keywords</string></dict>
    <dict><key>include</key><string>#types</string></dict>
    <dict><key>include</key><string>#integers</string></dict>
    <dict><key>include</key><string>#identifiers</string></dict>
  </array>
  <key>repository</key>
  <dict>
    <key>comments</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>name</key><string>comment.bslk</string>
          <key>match</key><string>(//).*$</string>
        </dict>
        <dict>
          <key>name</key><string>comment.block.bslk</string>
          <key>begin</key><string>/\*</string>
          <key>end</key><string>\*/</string>
        </dict>
      </array>
    </dict>
    <key>keywords</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>name</key><string>keyword.control.bslk</string>
          <key>match</key><string>\b(if|else|while|for|return|break|continue)\b</string>
        </dict>
        <dict>
          <key>name</key><string>keyword.other.bslk</string>
          <key>match</key><string>\b(let|global|const|func|len|sizeof|module|import|export|struct)\b</string>
        </dict>
        <dict>
          <key>name</key><string>constant.language.bslk</string>
          <key>match</key><string>\b(true|false|nullptr)\b</string>
        </dict>
      </array>
    </dict>
    <key>types</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>name</key><string>storage.type.bslk</string>
          <key>match</key><string>\b(bool|void|i8|i16|i32|i64|u8|u16|u32|u64|str|char|byte|isz|usz)\b[\*]*</string>
        </dict>
      </array>
    </dict>
    <key>identifiers</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>name</key><string>variable.other.bslk</string>
          <key>match</key><string>@?[+a-zA-Z_]\w*</string>
        </dict>
      </array>
    </dict>
    <key>integers</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>name</key><string>constant.numeric.dec.bslk</string>
          <key>match</key><string>[0-9]+</string>
        </dict>
        <dict>
          <key>name</key><string>constant.numeric.hex.bslk</string>
          <key>match</key><string>0x[0-9a-f]</string>
        </dict>
        <dict>
          <key>name</key><string>constant.numeric.oct.bslk</string>
          <key>match</key><string>0[0-7]+</string>
        </dict>
        <dict>
          <key>name</key><string>constant.numeric.bin.bslk</string>
          <key>match</key><string>0b[01]+</string>
        </dict>
      </array>
    </dict>
    <key>strings</key>
    <dict>
      <key>begin</key><string>"</string>
      <key>end</key><string>"</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>name</key><string>constant.character.escape.bslk</string>
          <key>match</key><string>\\.</string>
        </dict>
      </array>
    </dict>
  </dict>
  <key>uuid</key>
  <string>12345678-90ab-cdef-1234-567890abcdef</string>
</dict>
</plist>
